# Generated by Django 4.2 on 2024-01-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
    ]
