# Generated by Django 3.2.23 on 2024-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigScreen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(blank=True, help_text='区县', max_length=150, null=True)),
                ('grid', models.CharField(blank=True, help_text='网格', max_length=150, null=True)),
                ('residential_quarters', models.CharField(blank=True, help_text='小区', max_length=350, null=True)),
                ('zone_of_responsibility', models.CharField(blank=True, help_text='责任区', max_length=350, null=True)),
                ('packaging_and_maintenance', models.CharField(blank=True, help_text='包保装维', max_length=350, null=True)),
                ('userid', models.CharField(blank=True, help_text='用户账号', max_length=50, null=True)),
                ('userid_status', models.CharField(blank=True, help_text='用户账号状态', max_length=50, null=True)),
                ('satisfaction_status', models.CharField(blank=True, help_text='满意度状态', max_length=50, null=True)),
                ('confirm_satisfaction_time', models.CharField(blank=True, help_text='确认满意时间', max_length=50, null=True)),
                ('key_customer_groups', models.CharField(blank=True, help_text='重点客群类型', max_length=50, null=True)),
                ('internet_quality_rating', models.CharField(blank=True, help_text='上网质量评分', max_length=50, null=True)),
                ('scoring_by_install_and_maintain_services', models.CharField(blank=True, help_text='装维服务评分', max_length=150, null=True)),
                ('user_evaluation_methods', models.CharField(blank=True, help_text='用户评价方式', max_length=150, null=True)),
            ],
            options={
                'db_table': 'screen',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
    ]
