# Generated by Django 3.2.13 on 2024-01-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigScreen', '0003_alter_bigscreen_comprehensive_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bigscreen',
            table='tmp_big_data',
        ),
    ]
