# Generated by Django 3.2.13 on 2024-01-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigScreen', '0004_alter_bigscreen_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bigscreen',
            table='screen',
        ),
    ]
