# Generated by Django 4.2 on 2024-01-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigScreen', '0006_alter_bigscreen_comprehensive_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallMaintainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, help_text='用户账号', max_length=50, null=True)),
                ('score', models.CharField(blank=True, help_text='装维服务评分', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternetQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, help_text='用户账号', max_length=50, null=True)),
                ('score', models.CharField(blank=True, help_text='装维服务评分', max_length=150, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bigscreen',
            options={'verbose_name': '大屏', 'verbose_name_plural': '大屏'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
    ]
