# Generated by Django 4.2 on 2024-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigScreen', '0007_installmaintainscore_internetqualityscore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmaintainscore',
            options={'verbose_name': '装维服务', 'verbose_name_plural': '装维服务'},
        ),
        migrations.AlterModelOptions(
            name='internetqualityscore',
            options={'verbose_name': '上网质量', 'verbose_name_plural': '上网质量'},
        ),
        migrations.RemoveField(
            model_name='bigscreen',
            name='confirm_satisfaction_time',
        ),
        migrations.RemoveField(
            model_name='bigscreen',
            name='key_customer_groups',
        ),
        migrations.RemoveField(
            model_name='bigscreen',
            name='satisfaction_status',
        ),
        migrations.RemoveField(
            model_name='bigscreen',
            name='user_evaluation_methods',
        ),
        migrations.AlterField(
            model_name='internetqualityscore',
            name='score',
            field=models.CharField(blank=True, help_text='上网质量评分', max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='installmaintainscore',
            table='install',
        ),
        migrations.AlterModelTable(
            name='internetqualityscore',
            table='internet',
        ),
    ]
